name: execute-build

on:
  schedule:
    - cron: "0 0 * * *" #runs at 00:00 UTC everyday

jobs:
  build-cdn-list:
    runs-on: ubuntu-latest
    steps:
    - name: execute py script # run the run.py to get the latest data
        run: |
          python build.py 
